routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('layouts.education_theme.homepage');
});

Route::get('/emails', function () {
	$tutor_test = App\TutorTest::first();
	$tutor_candidate = App\TutorCandidate::first();
   return view('btn.emails.notify_tutor_candidates', compact('tutor_test', 'tutor_candidate'));
});

Auth::routes();

//DO NOT CHANGE ROUTE URL NAME /home
Route::get('/home', 'UsersController@myAccount')
		->name('home')
		->middleware('auth');

Route::get('/cart', [
		'as' => 'cart.index',
		'uses' => 'CartController@index'
	]);

Route::get('/subscriptions/select-packages', [
		'as' => 'purchase.select.packages',
		'uses' => 'SubscriptionsController@selectPackages'
	]);

Route::post('/subscriptions/select-packages/{package_ref_id}', [
	'as' => 'add.to.cart',
	'uses' => 'CartController@addToCart'
]);

Route::delete('/cart/empty', [
	'as' =>'empty.cart', 
	'uses' => 'CartController@emptyCart',
]);

Route::delete('/cart/remove-item/{row_id}', [
	'as' =>'remove.item', 
	'uses' => 'CartController@removeItem',
]);

Route::middleware(['auth', 'role:admin'])->group(function () {
	
	Route::get('/users', [
		'as' => 'users.index',
		'uses' => 'UsersController@index'
	]);

	Route::get('/clone-users/{user_id}', [
		'as' => 'clone.user',
		'uses' => 'UsersController@cloneUser'
	]);

	Route::get('/select-exam', [
		'as' => 'select-exam',
		'uses' => 'ExamsController@selectExam'
	]);

	Route::get('/courses/{course_id}/add-topics', [
		'as' => 'add.course.topics',
		'uses' => 'CoursesController@addCourseTopics'
	]);

	Route::post('/courses/{course_id}/add-topics', [
		'as' => 'save.course.topics',
		'uses' => 'CoursesController@saveCourseTopics'
	]);

	Route::get('/take-exam/{exam_id}', [
		'as' => 'take-exam',
		'uses' => 'ExamsController@takeExam'
	]);

	Route::post('/grade-exam/{exam_id}', [
		'as' => 'grade-exam',
		'uses' => 'ExamsController@gradeExam'
	]);

	Route::get('/view-questions/{course_id}', [
		'as' => 'view.questions',
		'uses' => 'QuestionsController@viewQuestions'
	]);

	Route::post('/add-topics/{course_id}', [
		'as' => 'add.topics',
		'uses' => 'QuestionsController@addTopics'
	]);


	Route::get('/update-exam/reviewed-completed/{exam_id}/{option}/{value}', [
		'as' => 'update.completed.reviewed',
		'uses' => 'ExamsController@updateCompletedOrReviewed'
	]);

	Route::get('/subscriptions', [
		'as' => 'subscriptions.index',
		'uses' => 'SubscriptionsController@index'
	]);

	Route::post('/subscriptions/{subscription_id}/create-free-subscription', [
		'as' => 'create.free.subscription',
		'uses' => 'SubscriptionsController@createFreeSubscription'
	]);	
});

Route::middleware(['auth', 'role:admin|staff'])->group(function () {
	Route::get('/staff/exam-upload-progress', [
		'as' => 'exam.upload.progress',
		'uses' => 'ExamsController@examUploadProgress'
	]);

	Route::get('/load-exam/{exam_id}', [
		'as' => 'load-exam',
		'uses' => 'ExamsController@loadExam'
	]);

	Route::post('/save-exam', [
		'as' => 'save.exam',
		'uses' => 'ExamsController@saveExam'
	]);

	Route::get('/show-question/{ref_id}', [
		'as' => 'show-question',
		'uses' => 'QuestionsController@showQuestion'
	]);

	Route::post('/update-question/{ref_id}', [
		'as' => 'update.question',
		'uses' => 'QuestionsController@updateQuestion'
	]);

	Route::get('/create-question/{exam_id}', [
		'as' => 'create.question',
		'uses' => 'QuestionsController@createQuestion'
	]);

	Route::post('/save-question/{exam_id}', [
		'as' => 'save.question',
		'uses' => 'QuestionsController@saveQuestion'
	]);
});


Route::middleware(['auth'])->group(function () {
	//To Purchase Subscription, an account must be made
	Route::get('/subscriptions/review', [
		'as' => 'review.subscriptions',
		'uses' => 'SubscriptionsController@reviewSubscriptions'
	]);	

	Route::post('/subscriptions/purchase', [
		'as' => 'purchase.subscriptions',
		'uses' => 'SubscriptionsController@purchaseSubscriptions'
	]);

	Route::get('/edit-account/{user_ref_id}', [
		'as' => 'edit.account',
		'uses' => 'UsersController@editAccount'
	]);

	Route::post('/edit-account/{user_ref_id}', [
		'as' => 'update.account',
		'uses' => 'UsersController@updateAccount'
	]);	
});

Route::middleware(['auth', 'role:admin|subscriber|free|mogi-student'])->group(function () {

	Route::get('/take-assessment/view-topics/{package_ref_id}', [
		'as' => 'view.topics',
		'uses' => 'AssessmentsController@viewTopics'
	]);

	Route::post('/take-assessment/{package_ref_id}', [
		'as' => 'take.assessment',
		'uses' => 'AssessmentsController@takeAssessment'
	]);

	Route::get('/take-assessment/res/{assessment_ref_id}', [
		'as' => 'resume.assessment',
		'uses' => 'AssessmentsController@resumeAssessment'
	]);

	Route::post('/pause-assessment/{package_ref_id}', [
		'as' => 'pause.assessment',
		'uses' => 'AssessmentsController@pauseAssessment'
	]);

	Route::post('/grade-assessment/{package_ref_id}', [
		'as' => 'grade.assessment',
		'uses' => 'AssessmentsController@gradeAssessment'
	]);

	Route::get('/view-results/{assessment_ref_id}', [
		'as' => 'view.results',
		'uses' => 'AssessmentsController@viewResults'
	]);

	Route::post('/report-issue/{question_ref_id}/{assessment_ref_id}', [
		'as' => 'report.issue',
		'uses' => 'AssessmentsController@reportIssue'
	]);

});


//Proficiency Exams
Route::group(['prefix' => 'proficiency-exams'], function(){
	Route::get('/', [
		'as' => 'proficiency.exams.info',
		'uses' => 'ProficiencyExamsController@proficiencyExamsInfo'
		]);

	Route::middleware(['auth', 'role:admin'])->group(function () {
		Route::get('/list', [
			'as' => 'proficiency.exams.list',
			'uses' => 'ProficiencyExamsController@index'
			]);
		
		Route::post('/store', [
			'as' => 'proficiency.store',
			'uses' => 'ProficiencyExamsController@store'
			]);

		Route::post('add-courses/{prof_exam_id}', [
			'as' => 'add.proficiency.courses',
			'uses' => 'ProficiencyExamsController@addProficiencyCourses'
			]);
	});

	Route::middleware(['auth'])->group(function () {
		Route::post('create-tutor-test', [
			'as' => 'create.tutor.test',
			'uses' => 'TutorTestsController@createTutorTest'
			]);

		Route::get('/view-test/{tutor_test_ref_id}', [
			'as' => 'view.tutor.test',
			'uses' => 'TutorTestsController@viewTutorTest'
			]);

		Route::get('/email-tutors/{tutor_test_ref_id}', [
			'as' => 'select.tutors',
			'uses' => 'TutorTestsController@selectTutors'
			]);

		Route::post('email-exams/{tutor_test_ref_id}', [
			'as' => 'email.tutor.test',
			'uses' => 'TutorTestsController@emailTutorTest'
			]);
		Route::post('resend-email/{tutor_test_ref_id}/{tutor_candidate_ref_id}', [
			'as' => 'resend.tutor.test',
			'uses' => 'TutorTestsController@resendTutorEmail'
			]);

		Route::get('/view-performance/{tutor_test_ref_id}/{tutor_candidate_ref_id}', [
			'as' => 'view.tutor.results',
			'uses' => 'TutorTestsController@viewTutorResults'
			]);

		Route::get('/tutors/take-test/{tutor_test_ref_id}/{tutor_candidate_ref_id}', [
			'as' => 'take.tutor.test',
			'uses' => 'TutorTestsController@takeTutorTest'
			]);
		
		Route::post('/tutors/subscription/{tutor_test_ref_id}/{tutor_candidate_ref_id}', [
			'as' => 'purchase.tutor.test',
			'uses' => 'TutorTestsController@purchaseTutorTest'
			]);

		Route::post('/tutors/grade-test/{tutor_test_ref_id}/{tutor_candidate_ref_id}', [
			'as' => 'grade.tutor.test',
			'uses' => 'TutorTestsController@gradeTutorTest'
			]);
	});
});

app/Subscription.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Carbon;
use App\Role;
use App\Package;
use App\Payment;

class Subscription extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'id'
    ];
    //Relationships
    public function users(){
        return $this->belongsToMany('App\User')
                    ->withTimestamps()
                    ->withPivot('package_id', 'payment_id', 'price', 'start_date', 'end_date', 'free', 'notes', 'deleted_at');
    }

    //Methods
    public function active(){
        //Active subscriptions/packages
        if ($this->pivot->start_date <= Carbon\Carbon::now() 
            && $this->pivot->end_date >= Carbon\Carbon::now()
            && $this->pivot->deleted_at == null
            && $this->tutor_test == 0) {
            return true;
        }
        
        return false;
    }

    public function package(){
        $package = Package::find($this->pivot->package_id);

        return $package;
    }

    public function payment(){
        $payment = Payment::find($this->pivot->payment_id);

        return $payment;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

use Carbon;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $dates = ['deleted_at', 'last_login_date'];
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'ref_id', 'first_name', 'last_name', 'email', 'phone', 'school', 'city', 'state', 'zip', 'country', 'password',
    ];

    /**
     * Accessor to create full name of user
     * @return string 
     */
    public function getFullNameAttribute()
    {
        return $this->first_name . " " . $this->last_name;
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    //Relationships
    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function customer(){
        return $this->hasOne('App\Customer');
    }

    public function payments(){
        return $this->hasMany('App\Payment');
    }

    public function assessments(){
        return $this->hasMany('App\Assessment');
    }

    public function tutor_tests(){
        return $this->hasMany('App\TutorTest');
    }

    public function tutor_candidates(){
        return $this->hasMany('App\TutorCandidate');
    }

    public function questions(){
        //For Staff, questions submitted by user when uploading exams
        return $this->hasMany('App\Question', 'submitted_by');
    }

    public function exams(){
        //For Staff, questions submitted by user when uploading exams
        return $this->hasMany('App\Exam', 'submitted_by');
    }

    //Methods
    public function exams_uploaded(){
        //For Staff
        $exams = $this->exams;
        foreach ($this->questions as $question) {
              if ($question->exam) {
                  $exams->push($question->exam);
              }
          }  

        return $exams->unique();
    }

    public function courses_uploaded(){
        //For Staff-- NOT USED!
        $courses = collect([]);

        foreach ($this->exams as $exam) {
              $courses->push($exam->course);
          }  

        foreach ($this->questions as $question) {
              $courses->push($question->exam->course);
          }  

          return $courses->unique();
    }

    public function subscriptions(){
        return $this->belongsToMany('App\Subscription')
                    ->withTimestamps()
                    ->withPivot('package_id', 'payment_id', 'price', 'start_date', 'end_date', 'free', 'notes', 'deleted_at');
    }

    //Methods
    public function hasRole($roles) 
    { 
        if (is_array($roles)) {
            foreach ($roles as $role) 
            {
                if ($this->roles->contains('role', $role))
                    return true;
            }
        }
        
        return $this->roles->contains('role', $roles);
    }

    public function isAdmin()
    {
        if ($this->hasRole(['banned'])) 
        {
            return false;
        }

        return $this->hasRole(['super-user', 'admin']);
    }

    public function isStaff()
    {
        if ($this->hasRole(['banned'])) 
        {
            return false;
        }

        return $this->hasRole(['staff', 'admin', 'super-user']);
    }

    public function addRole($role) 
    { 
        if (!$this->hasRole($role)) {
            return $this->roles()->save(Role::whereRole($role)->firstOrFail());     
        }  
    }

    public function removeRole($role) 
    { 
        if ($this->hasRole($role)) {
            $role_id = Role::whereRole($role)->firstOrFail()->id;
            return $this->roles()->detach($role_id);     
        }  
    }

    public function active_subscriptions(){
        //***USED IN GATE IN AuthServiceProvider
        //BUILDER
        return $this->subscriptions()
                    ->where('start_date', '<=', Carbon\Carbon::now())
                    ->where('end_date', '>', Carbon\Carbon::now())
                    ->wherePivot('deleted_at', null);
    }
}

resources/views/btn/subscriptions/index.blade.php
@extends('layouts.education_theme.template')

@section('content')
	<h2>Subscriptions</h2>

	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Duration</th>
				<th>Price</th>
				<th></th>				
			</tr>
		</thead>
		<tbody>
			@foreach ($subscriptions as $subscription)
				<tr>
					<td>{{$subscription->id}}</td>
					<td>{{$subscription->name}} 
						@if (!$subscription->active)
							<b style="color:darkred">Not Active</b>
						@endif
						<br>
						{{$subscription->description}}
					</td>
					<td>{{$subscription->duration}}</td>
					<td>${{$subscription->price}}<br>
						${{$subscription->sale_price}} (Sale)
						@if ($subscription->on_sale)
							<br><b style="color:darkred">On Sale</b>
						@endif
					</td>
					<td>
						{!! Form::open(['method' => 'POST', 'route' => ['create.free.subscription', $subscription->id], 'class' => 'form-horizontal', 'id' => "create".$subscription->id]) !!}
						
							<div class="row">
								<div class="col-md-6">
									<div class="form-group{{ $errors->has('user_id') ? ' has-error' : '' }}">
								        {!! Form::label('user_id', 'Free Users') !!}
								        {!! Form::select('user_id', $free_users, null, ['id' => 'user_id', 'class' => 'form-control', 'required' => 'required',]) !!}
								        <small class="text-danger">{{ $errors->first('user_id') }}</small>
								    </div>	
								</div>
								<div class="col-md-6">
									<div class="form-group{{ $errors->has('package_id') ? ' has-error' : '' }}">
									    {!! Form::label('package_id', 'Package') !!}
									    {!! Form::select('package_id',$packages, null, ['id' => 'package_id', 'class' => 'form-control', 'required' => 'required']) !!}
									    <small class="text-danger">{{ $errors->first('package_id') }}</small>
									</div>
								</div>
							</div>
						    							
						    <div class="btn-group pull-right">
						        {!! Form::submit("Add", ['class' => 'btn btn-success']) !!}
						    </div>
						
						{!! Form::close() !!}
					</td>
				</tr>	
			@endforeach
			
		</tbody>
	</table>

	<hr>
	<h2>Subscribers</h2>
	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Subscription</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach ($subscribers as $subscriber)
				<tr>
					<td>{{$subscriber->id}}</td>
					<td>{{$subscriber->full_name}}</td>
					<td>
						@if ($subscriber->subscriptions)
							@foreach ($subscriber->subscriptions as $subscription)
								<div class="col-md-3">
									<b>Name:</b> {{$subscription->name}}<br>
									<b>Start:</b> {{Carbon\Carbon::parse($subscription->pivot->start_date)->format('m/d/Y')}} <br>
									<b>End:</b> {{Carbon\Carbon::parse($subscription->pivot->end_date)->format('m/d/Y')}}<br>
									<b>Package:</b> {{$subscription->package()->title}}

									@if ($subscription->pivot->free)
										<br><b style="color:darkblue">Free Subscription</b>
									@endif	
								</div>
								
							@endforeach

						@endif

					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@endsection

resources/views/btn/subscriptions/payment_failed.blade.php
@extends('layouts.education_theme.template')

@section('content')
	<h2>Payment Failed</h2>
	We were unable to process your payment.  Please try again.
@endsection

resources/views/btn/subscriptions/purchase_subscription.blade.php
@extends('layouts.education_theme.template')

@section('content')
	<h2>Review Subscription</h2>
	<div class="col-md-6">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Course Package</th>
					<th>Subscription</th>
					<th>Price</th>
				</tr>
			</thead>
			<tbody>
				@foreach (Cart::content() as $cart_item)
					<tr>
						<td>
							{{$cart_item->options->package_name}}<br>
						</td>
						<td>
							{{$cart_item->name}} - {{$cart_item->model->duration}} Weeks
						</td>
						<td>${{$cart_item->price}}</td>
					</tr>
				@endforeach
				<tr>
					<td></td>
					<td></td>
					<td><b>${{number_format(Cart::subtotal(),0)}}</b></td>
				</tr>
			</tbody>
		</table>	
	</div>

	<div class="col-md-6">
		{!! Form::open(['method' => 'POST', 'route' => 'purchase.subscriptions', 'class' => 'form-horizontal', 'id' => 'payment-form']) !!}
		
		    @include('layouts.stripe_form')	
		
			<div class="form-group">
			    <div class="checkbox{{ $errors->has('beta') ? ' has-error' : '' }}">
			        <label for="beta">
			            {!! Form::checkbox('beta', '1', null, ['id' => 'beta', 'required']) !!} <span>I understand that this is a <b>Beta version</b> and may have errors.</span>
			        </label>
			    </div>
			    <small class="text-danger">{{ $errors->first('beta') }}</small>
			</div>

			<div class="form-group">
			    <div class="checkbox{{ $errors->has('refund') ? ' has-error' : '' }}">
			        <label for="refund">
			            {!! Form::checkbox('refund', '1', null, ['id' => 'refund', 'required']) !!} <span>I understand this subscription is <b>non-refundable</span>.
			        </label>
			    </div>
			    <small class="text-danger">{{ $errors->first('refund') }}</small>
			</div>


		    <div class="btn-group pull-right">
		        {!! Form::submit("Purchase Subscription", ['class' => 'btn btn-primary']) !!}
		    </div>
		
		{!! Form::close() !!}
	</div>
	
@endsection

resources/views/btn/subscriptions/select_packages.blade.php
@extends('layouts.education_theme.template')
@section('page_title', 'Subscriptions')
@section('content')
	<h2>Select Subscription
	@if (Cart::count())
		<div class="pull-right">
			<a href="#cart" class="btn btn-lg btn-primary">
				<img alt="" width="35" src="{{asset('img/education_theme/icons/icon-cart-grey.svg')}}"> View Cart
			</a>
			
		</div>
	@endif
	</h2>
	<div class="row">
		<div class="col-md-12">
			<h4><b>Exams Available In The Following Departments: 
			@foreach ($departments as $department)
				<a href="#{{$department}}">{{$department}}</a>,
			@endforeach		
			 more to come!
			 </b></h4>
		</div>
	</div>
	<br>
	Please note you are purchasing a discounted subscription to a <b>Beta version</b>.  The package & questions may have a few mistakes such as e.g. spelling or formatting errors.  Any feedback helps us improve this service to you and other students and is greatly appreciated!<br><br>
	@include('layouts.education_theme.partials.pricing_table')
	


	@if (auth()->user() && auth()->user()->active_subscriptions()->count())
		You currently have the following subscription(s):
		@foreach (auth()->user()->active_subscriptions()->get() as $active_subscription)
			<li><b>{{$active_subscription->package()->title}}</b> <small>(Ending {{Carbon\Carbon::parse($active_subscription->pivot->end_date)->diffForHumans()}})</small></li>
		@endforeach
	@endif
	<div class="col-md-8">
		@foreach ($departments as $department)
			<h2 id="{{$department}}"><b style="color:darkgreen; font-family: serif">{{strtoupper($department)}}</b></h2>
			<table class="table">
				<tbody>
					@foreach ($packages->where('department', $department)->sortby('order') as $package)
						<tr>
							<td>
								<h3>{{$package->title}}</h3> <br>

								@if ($package->description)
									{{$package->description}}<br><br>
								@endif
								
								<a data-toggle="collapse" data-target="#topics_{{$package->ref_id}}">{{-- {{$package->active_topics()->count()}} Topics, {{$package->questions()->count()}} Questions --}} View Topics</a>
								<br>

								<small>Click for the number of questions for each topic.</small>
								<div id="topics_{{$package->ref_id}}" class="collapse">
									
									@foreach ($package->active_topics() as $topic)
										<li>{{$topic->topic}} ({{$topic->questions->count()}})</li>
									@endforeach
								</div>
							</td>
							<td>
								
								{!! Form::open(['method' => 'POST', 'route' => ['add.to.cart', 'package_ref_id' => $package->ref_id], 'class' => 'form-horizontal', 'id' => $package->ref_id]) !!}
									@foreach ($subscriptions->sortByDesc('duration') as $subscription)
										<div class="radio{{ $errors->has('$subscription_id[$package->ref_id]') ? ' has-error' : '' }}">
										    <label>
										        {!! Form::radio("subscription_id[$package->ref_id]",$subscription->ref_id,  null, ['required', 'class' => 'pull-left']) !!} 
										        <span>{{$subscription->name}} - 

										        	@if ($subscription->on_sale)
		                                                <s>${{number_format($subscription->price,0)}}</s>  ${{number_format($subscription->sale_price,0)}}
		                                            @else
		                                        		${{number_format($subscription->price,0)}}
		                                            @endif
		                                         </span>
										         <br>
										        
										        {{$subscription->duration}} Weeks
										    </label>
										    <small class="text-danger">{{ $errors->first('$subscription_id[$package->ref_id]') }}</small>
										</div>
									@endforeach
									<br>
									{!! Form::submit("Add To Cart", ['class' => 'col-md-4 col-sm-4 btn btn-primary']) !!}
								{!! Form::close() !!}
								<br><br>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
			<hr>
		@endforeach
	</div>

	<div class="col-md-4">
		<h2 id="cart">Cart</h2>
		<table class="table">
			@forelse (Cart::content() as $cart_item)
				<tr>
					<td>{!! Form::open(['method' => 'DELETE', 'route' => ['remove.item', 'row_id' => $cart_item->rowId], 'class' => 'delete']) !!}	
							<div class="btn-group pull-right">
						        {!! Form::submit("X", ['class' => 'btn btn-sm btn-danger']) !!}
						    </div>
						{!! Form::close() !!}
					</td>
					<td>{{$cart_item->options->package_name}} - {{$cart_item->name}}<br>
						<small>{{$cart_item->model->duration}} Weeks</small>

					</td>
					<td>${{$cart_item->price}}</td>
				</tr>
			@empty
				<tr><td><em>No Items In Cart</em></td></tr>
			@endforelse
			@if (Cart::count())
				<tr>
					<td></td>
					<td></td>
					<td><b>${{number_format(Cart::subtotal(),0)}}</b><br><br>
						{!! Form::open(['method' => 'GET', 'route' => 'review.subscriptions', 'class' => 'form-horizontal']) !!}
						    <div>
						        {!! Form::submit("Proceed To Checkout", ['class' => 'btn btn-success']) !!}
						    </div>
						
						{!! Form::close() !!}
					</td>
				</tr>
			@endif
		</table>
	</div>
@endsection